services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: ./web-scraping-project/Dockerfile
    ports:
      - "3000:3000"